version: 2

workflows:
  version: 2
  full_test:
    jobs:
      - prep-deps-npm
      - prep-build:
          requires:
            - prep-deps-npm
      - test-lint:
          requires:
            - prep-deps-npm
      - test-unit:
          requires:
            - prep-deps-npm
      - test-e2e-chrome:
          requires:
            - prep-deps-npm
# TODO: Broken
#      - test-e2e-firefox:
#          requires:
#            - prep-deps-npm
      - all-tests-pass:
          requires:
            - test-lint
            - test-e2e-chrome
#            - test-e2e-firefox
            - test-unit
      - job-publish-prerelease:
          requires:
            - prep-deps-npm
            - prep-build
            - all-tests-pass
      - job-publish-release:
          filters:
            branches:
              only: master
          requires:
            - job-publish-prerelease
jobs:
  prep-deps-npm:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.0-dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm 6 + deps via npm
          command: |
           sudo npm install -g npm@6 && npm install --no-save
      - persist_to_workspace:
          root: .
          paths:
          - node_modules
      - save_cache:
          key: v1.0-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  prep-build:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build:dist
          command: npm run dist
      - run:
          name: build:debug
          command: find dist/ -type f -exec md5sum {} \; | sort -k 2
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - builds
  test-lint:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm run lint
  test-unit:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: test:coverage
          command: npm run test:coverage
  test-e2e-firefox:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: test:e2e:firefox
          command: npm run test:e2e:firefox
  test-e2e-chrome:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: test:e2e:chrome
          command: npm run test:e2e:chrome
  job-publish-prerelease:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm run zip
      - persist_to_workspace:
          root: .
          paths:
            - releases
  job-publish-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=v$(jq -r '.version' package.json)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./releases/
      - store_artifacts:
          path: releases
          destination: releases
  all-tests-pass:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - run:
          name: All Tests Passed
          command: echo 'weew - everything passed!'

